version: '3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.2
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.2.2
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    volumes:
      - broker-data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_LOG_RETENTION_HOURS: 0
      KAFKA_LOG_RETENTION_MINUTES: 10

  schema-registry:
    image: confluentinc/cp-schema-registry:7.2.2
    restart: always
    depends_on:
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  redpanda-console:
    #image: docker.redpanda.com/vectorized/console:master-0a8fce8
    image: docker.redpanda.com/vectorized/console:latest
    restart: always
    depends_on:
      - broker
      - schema-registry
    ports:
      - "9000:8080"
    environment:
      SERVER_BASEPATH: /redpanda
      #METRICSNAMESPACE: redpanda-console
      KAFKA_BROKERS: ${KAFKA_BROKERS:-broker:29092}
      KAFKA_SCHEMAREGISTRY_ENABLED: "true"
      KAFKA_SCHEMAREGISTRY_URLS: "http://schema-registry:8081"
      CONNECT_ENABLED: "true"
      CONNECT_CLUSTERS_NAME: connect-cluster
      CONNECT_CLUSTERS_URL: "http://connect:8083"

  ksqldb-server:
    image: confluentinc/cp-ksqldb-server:7.2.2
    hostname: ksqldb-server
    container_name: ksqldb-server
    depends_on:
      - broker
      - schema-registry
    ports:
      - "8088:8088"
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: broker:29092
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      # KSQL_KSQL_CONNECT_URL: ''

  ksqldb-cli:
    image: confluentinc/cp-ksqldb-cli:7.2.2
    container_name: ksqldb-cli
    depends_on:
      - broker
      - schema-registry
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true

  zilla:
     image: ghcr.io/aklivity/zilla:latest
     container_name: zilla
     command:  start -v -e
     restart: unless-stopped
     depends_on:
       - broker
     ports:
       - "7114:7114"
     environment:
       KAFKA_HOST: "broker"
       KAFKA_PORT: "9092"
       KEYSTORE_PASSWORD: "generated"
       API_URL: "http://localhost:7114"
     volumes:
       - ./zilla.yml:/etc/zilla/zilla.yaml

volumes:
  zookeeper-data:
  zookeeper-log:
  broker-data:
  connect-data:


networks:
  default:
    name: webinar-network

