# ====================================
# Copyright (C) 2020  Commsignia Ltd
# http://commsignia.com
# All rights reserved
# ------------------------------------
# Date: Oct 2, 2020
# Author: Timót Tarjáni <timot.tarjani@commsignia.com>
# Project: MessageLake
# ====================================

server:
    port: 8081
    tomcat.max-threads: 15
    servlet.context-path: /meetup

logging:
    level.root: INFO
    file:
        path: /var/log/meetup
        name: ${logging.file.path}/meetup/meetup.log

spring:
    application.name: meetup-demo
    kafka:
        bootstrap-servers: localhost:9092
        properties:
            spring.json.add.type.headers: false
        consumer:
            group-id: ${spring.application.name}
            key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            properties:
                spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
                spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        listener:
            concurrency: 10
