helmDefaults:
  wait: true
  createNamespace: true

repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: zilla
  namespace: default
  chart: oci://ghcr.io/aklivity/charts/zilla
  version: ^0.9.0
  set:
    # single value loaded from a local file, translates to --set-file foo.config=path/to/file
    - name: "zilla\\.yaml"
      file: ../zilla.yml

- name: prometheus
  namespace: default
  chart: prometheus-community/prometheus
  set:
  - name: rbac.create
    value: false