repositories:
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts

releases:
- name: zilla
  chart: oci://ghcr.io/aklivity/charts/zilla
  version: 0.9.81
  set:
  - name: file 
    value: zilla.yaml:../zilla.yml

- name: prometheus
#  namespace: prometheus
  chart: prometheus-community/prometheus
  set:
  - name: rbac.create
    value: false