helmDefaults:
  wait: true
  createNamespace: true

repositories:
- name: trendency 
  url: https://gitlab.trendency.hu/api/v4/projects/2443/packages/helm/devel
  username: timot.tarjani
  password: QvxdaShykq9bH9LyUuHu
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: redpanda
  url: https://charts.redpanda.com
- name: licenseware
  url: https://licenseware.github.io/charts/
#- name: kong
#  url: https://charts.konghq.com
#- name: prometheus-community
#  url: https://prometheus-community.github.io/helm-charts
#- name: druid
#  url: https://asdf2014.github.io/druid-helm/

releases:

- name: kafka
  namespace: mndwrk-demo
  chart: bitnami/kafka
  version: 30.0.3
  values: 
    - values/kafka.yaml

- name: schema-registry
  namespace: mndwrk-demo
  chart: bitnami/schema-registry
  version: 21.0.0
  values: 
    - values/schema-registry.yaml
 
- name: kafka-connect
  namespace: mndwrk-demo
  chart: licenseware/kafka-connect
  version: 0.2.1
  values:
    - values/kafka-connect.yaml

- name: ksqldb
  namespace: mndwrk-demo
  chart: licenseware/ksqldb
  version: 0.4.1
  values:
    - values/ksqldb.yaml

- name: redpanda-console
  namespace: mndwrk-demo
  chart: redpanda/console
  version: 0.7.26
  values:
    - values/redpanda-console.yaml

- name: apisix
  namespace: mndwrk-demo
  chart: oci://registry-1.docker.io/bitnamicharts/apisix
  version: 3.5.1
  values:
    - values/apisix.yaml

- name: zilla
  namespace: mndwrk-demo
  chart: oci://ghcr.io/aklivity/charts/zilla
  version: ^0.9.0
  set:
    - name: "zilla\\.yaml"
      file: ./zilla.yml
    - name: "service.type"
      value: "LoadBalancer"
    - name: "service.ports[0].name"
      value: zilla
    - name: "service.ports[0].port"
      value: 8080
    - name: "service.ports[0].targetName"
      value: zilla
    - name: "configMapPairs.KAFKA_BOOTSTRAP_SERVER"
      value: kafka:9092
    - name: "configMapPairs.SASL_USERNAME"
      value: user1
    - name: "configMapPairs.SASL_PASSWORD"
      value: kafka-user-passwords.secret

- name: keycloak
  namespace: mndwrk-demo
  chart: bitnami/keycloak
  version: 22.0.0
  values:
    - values/keycloak.yaml


##
##- name: prometheus
##  namespace: mndwrk-demo
#  chart: prometheus-community/prometheus
#  set:
#  - name: rbac.create
#    value: false
    
# - name: druid
#   namespace: mndwrk-demo
#   chart: druid/druid
#   version: 30.0.5
# 
# - name: spring-dataflow
#   namespace: mndwrk-demo
#   chart: bitnami/spring-cloud-dataflow
#   version: 31.0.0
#   set:
#     - name: rabbitmq.enabled
#       value: false
#     - name: skipper.enabled
#       value: false
#
#- name: kong
#  namespace: mndwrk-demo
#  chart: kong/kong
#  version: 2.40.0
#  set: 
#    - name: admin.enabled
#      value: true 
#    - name: admin.http.enabled
#      value: true
#